backend:
  name: git-gateway
  branch: main

publish_mode: simple

media_folder: "images"
public_folder: "/images"

locale: "az"

collections:
  - name: "articles"
    label: "Məqalələr"
    files:
      - name: "articles"
        label: "Bütün məqalələr"
        file: "content/articles.json"
        fields:
          - label: "Məqalələr"
            name: "articles"
            widget: "list"
            label_singular: "Məqalə"
            summary: "{{title}} — {{date}}"
            fields:
              - { label: "Tarix", name: "date", widget: "string", hint: "Məsələn: 15 Sen 2026" }
              - label: "Kateqoriya"
                name: "tag"
                widget: "select"
                options: ["sağlamlıq", "hüquq", "hekayə"]
              - { label: "Başlıq", name: "title", widget: "string" }
              - { label: "Təsvir", name: "desc", widget: "text" }

  - name: "podcast"
    label: "Podcast"
    files:
      - name: "episodes"
        label: "Bütün bölümlər"
        file: "content/episodes.json"
        fields:
          - label: "Bölümlər"
            name: "episodes"
            widget: "list"
            label_singular: "Bölüm"
            summary: "Bölüm {{num}} — {{title}}"
            fields:
              - { label: "Bölüm nömrəsi", name: "num", widget: "string", hint: "Məsələn: 13" }
              - { label: "Başlıq", name: "title", widget: "string" }
              - { label: "Təsvir", name: "desc", widget: "text" }
              - { label: "Müddət", name: "dur", widget: "string", hint: "Məsələn: 30 dəq" }
